name: CI/CD Pipeline

on: [push]

jobs:
  ci-cd:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          echo " Building Docker image..."
          docker build -t sammreen .

      - name: Deploy Docker container
        run: |
          echo " Deploying Docker container..."
          docker stop sammreen || true
          docker rm sammreen || true
          docker run -d --name sammreen -p 80:80 sammreen

      - name: Test if the server is up
        run: |
          echo " Testing if the server is up..."
          sleep 10
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1)
          if [ "$STATUS_CODE" -eq 200 ]; then
            echo " Server is up and running on localhost."
          else
            echo " Server is not up. Status code: $STATUS_CODE"
            exit 1
          fi
